# Connection logging methods

LoggingMethod:
  SingleFile: False
  UUIDFiles: False
  MYSQL: False
  MINECRAFTLOG: False

#Database

Database:
  logConnectionAttempts: False
  Address: 
  Username: 
  Password: 
  Name: 
  Connection_log_table_name: 
  Plugin_log_table_name: 