name: ConnectionInfo
main: net.comdude2.plugins.connectioninfo.main.ConnectionInfo
version: 1.3.56
author: comdude2
description: A Minecraft plugin that monitors client and server connections and records information.
depend: [ComLibrary]
commands:
   debugger:
      description: Run the debugger for ConnectionInfo.
      usage: /<command> [sub]
      permission: connectioninfo.debugger
      permission-message: You don't have <permission>
   connectioninfo:
      description: Main command for ConnectionInfo.
      usage: /<command> [sub]
      permission: connectioninfo.main
      permission-message: You don't have <permission>
   ci:
      description: Main command for ConnectionInfo.
      usage: /<command> [sub]
      permission: connectioninfo.main
      permission-message: You don't have <permission>
   cinfo:
      description: Main command for ConnectionInfo.
      usage: /<command> [sub]
      permission: connectioninfo.main
      permission-message: You don't have <permission>