name: ConnectionInfo
main: net.comdude2.plugins.connectioninfo.main.ConnectionInfo
version: 1.3.56
author: comdude2
description: A Minecraft plugin that monitors client and server connections and records information.
depend: [ComLibrary]